### ISSUE TITLE
Improve SCSS

### ISSUE THREAD

**Issue by iamabdus** [tafcoder/sleek-dashboard#2]
**Here are some tasks need to be done to improve SCSS:**

- [x] Import bootstrap scss from NPM modules instead manually
- [x] Refactor scss variables to overwrite bootstrap default
- [x] Change SCSS file structure to meet [Bootstrap guideline](https://getbootstrap.com/docs/4.1/getting-started/theming/)

**Comment by dipujscoder** [comment]
Some unsolved work pending

**Comment by iamabdus** [comment]
#
