### ISSUE TITLE
Can't hide the menu after expanding it on small devises 

### ISSUE THREAD

**Issue by CrestApps** [tafcoder/sleek-dashboard#243]
On a small device like iPad or a phone, the left menu automatically closes as it should which is great. However, after the "Toggle navigation" button is clicked to show the menu, the "Toggle navigation" button itself will get covered preventing you from toggling the menu again.

In other words, after showing the menu on small devices, no easy way to close the menu again.

**Comment by missionary1995** [comment]
im having the same issue

**Comment by missionary1995** [comment]
i solved the issue...it seems like there is a problem with the sleek.bundle.js file included in the github project files..

i went to their demo website and downloaded their sleek.bundle.js file from there

here is the link
https://sleek.tafcoder.com/assets/js/sleek.bundle.js

just download and replace and it will start working!
