### ISSUE TITLE
Long brand name

### ISSUE THREAD

**Issue by sama55** [tafcoder/sleek-dashboard#262]
Thank you for your nice theme.
Longer brand name will not hide the sidebar on mobile.
For example, from "Sleek Dashboard" to "Sleek Dashboard aaa bbb".
Thanks for your help.

**Comment by sama55** [comment]
I added the following CSS.

.app-brand .brand-name {
  line-height: 1.5rem;
  max-width: 180px;
  overflow: hidden;
}

**Comment by faruqtaf** [comment]
Nice! we will fix it soon
