### ISSUE TITLE
Long menu

### ISSUE THREAD

**Issue by sama55** [tafcoder/sleek-dashboard#268]
When menu on left sidebar is long, caret disappears.
For exmaple, 
Before: Data Tables
After: Data TablesＡＡＡＡＡＡＡＡＡＡ

**Comment by sama55** [comment]
Fixed with below CSS (This may be incomplete fix).
.sidebar .sub-menu > li .sub-menu {
    max-width: 160px;
    overflow: hidden;
}

**Comment by faruqtaf** [comment]
Thanks for the fix :)
