### ISSUE TITLE
Modal problem

### ISSUE THREAD

**Issue by sama55** [tafcoder/sleek-dashboard#273]
Large modal is shown under sidebar.

**Comment by sama55** [comment]
z-index of sidebar is 1060. This may be intention, but it causes problems.
I changed it like this in my custom CSS:
.sidebar-fixed-offcanvas .left-sidebar, .sidebar-fixed .left-sidebar {
	z-index: 999;
}
Reference about bootstrap.

$zindex-dropdown:          1000 !default;
$zindex-sticky:            1020 !default;
$zindex-fixed:             1030 !default;
$zindex-modal-backdrop:    1040 !default;
$zindex-modal:             1050 !default;
$zindex-popover:           1060 !default;
$zindex-tooltip:           1070 !default;

**Comment by faruqtaf** [comment]
Nice! we will fix it soon.
