### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by mrcat323** [tafcoder/sleek-dashboard#284]
Hey guys, nice job.
Add ability to remove and move todos, functionality is nice though but lack of let's say __responsibility__ for this task by user. For example I added todo, and I want to __remove__ it, how can I do that ? Or reorder todos. Add that **"feature"**

**Comment by iamabdus** [comment]
Let's try to do something similar to https://github.com/themaxsandelin/todo

**Comment by mrcat323** [comment]
@iamabdus nice, waiting for it

**Comment by mrcat323** [comment]
waiting for this feature being applied :cat2:
